# Dog and Cat Classification

In [1]:
import tensorflow as tf

In [2]:
import os
!pip install opencv-python

In [3]:
import cv2
import matplotlib.pyplot as plt

In [4]:
dir=r"C:\Users\gowri\Downloads\archive (3)\training_set\training_set"

In [5]:
category=["cats","dogs"]
df=[]

In [6]:
for i in category:
    path=os.path.join(dir,i)
    for img in os.listdir(path):
        try:
            img_path=os.path.join(path,img)
            label=category.index(i)
            img_arr=cv2.imread(img_path,cv2.IMREAD_GRAYSCALE)
            img_arr=cv2.resize(img_arr,(60,60))
            df.append([img_arr,label])
        except Exception as e:
            print(img_path)       

C:\Users\gowri\Downloads\archive (3)\training_set\training_set\cats\_DS_Store
C:\Users\gowri\Downloads\archive (3)\training_set\training_set\dogs\_DS_Store


In [7]:
import random
random.shuffle(df)

In [8]:
x,y=[],[]
for i,j in df:
    x.append(i)
    y.append(j)

In [9]:
x

[array([[161, 153, 152, ..., 136, 132, 131],
        [160, 153, 156, ..., 134, 127, 129],
        [154, 153, 160, ..., 128, 122, 138],
        ...,
        [155, 162, 157, ..., 186, 185, 181],
        [151, 154, 156, ..., 192, 196, 192],
        [154, 154, 152, ..., 191, 190, 184]], dtype=uint8),
 array([[  1,   1,   1, ..., 244, 244, 244],
        [  1,   1,   1, ..., 242, 244, 243],
        [  1,   1,   1, ..., 237, 244, 242],
        ...,
        [252, 238, 242, ...,  91,  61, 113],
        [148, 198, 120, ...,  97, 121,  93],
        [173, 158, 128, ...,  91,  71,  83]], dtype=uint8),
 array([[207, 205, 209, ..., 173, 162, 167],
        [203, 206, 204, ..., 179, 168, 162],
        [198, 198, 175, ..., 179, 162, 165],
        ...,
        [190, 212, 210, ..., 238, 232, 219],
        [204, 212, 214, ..., 234, 228, 206],
        [211, 213, 216, ..., 235, 231, 230]], dtype=uint8),
 array([[ 17,  12,   2, ...,  94, 104, 114],
        [ 20,  15,   4, ...,  99, 109, 118],
        [ 19,  1

In [10]:
import numpy as np
y=np.array(y)
y.reshape(-1,1)

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [11]:
x=tf.keras.utils.normalize(x)
x=x.reshape(-1,60,60,1)
x

array([[[[0.13892692],
         [0.13202372],
         [0.13116082],
         ...,
         [0.11735442],
         [0.11390282],
         [0.11303992]],

        [[0.13857624],
         [0.13251353],
         [0.13511184],
         ...,
         [0.1160576 ],
         [0.10999489],
         [0.1117271 ]],

        [[0.13367215],
         [0.13280414],
         [0.13888015],
         ...,
         [0.11110412],
         [0.10589612],
         [0.11978413]],

        ...,

        [[0.12967248],
         [0.13552865],
         [0.13134567],
         ...,
         [0.15560697],
         [0.15477037],
         [0.15142399]],

        [[0.12251913],
         [0.12495329],
         [0.12657606],
         ...,
         [0.15578592],
         [0.15903146],
         [0.15578592]],

        [[0.12938372],
         [0.12938372],
         [0.12770341],
         ...,
         [0.16046942],
         [0.15962926],
         [0.15458834]]],


       [[[0.00081864],
         [0.00081864],
         [0.00

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Dense,Flatten

In [13]:
model=Sequential([
    Conv2D(64,(3,3),activation="relu"),
    MaxPooling2D((2,2)),
    Conv2D(64,(3,3),activation="relu"),
    MaxPooling2D((2,2)),
    Flatten(),
    Dense(128,activation="relu"),
    Dense(2,activation="sigmoid")
])

In [14]:
model.compile(loss="sparse_categorical_crossentropy",optimizer="adam",metrics=['accuracy'])

In [15]:
model.fit(x,y,epochs=10,batch_size=250)

Epoch 1/10
33/33 [==============================] - 161s 4s/step - loss: 0.6909 - accuracy: 0.5212
Epoch 2/10
33/33 [==============================] - 110s 3s/step - loss: 0.6651 - accuracy: 0.5939
Epoch 3/10
33/33 [==============================] - 178s 5s/step - loss: 0.6592 - accuracy: 0.6024
Epoch 4/10
33/33 [==============================] - 152s 5s/step - loss: 0.6343 - accuracy: 0.6415
Epoch 5/10
33/33 [==============================] - 125s 4s/step - loss: 0.6046 - accuracy: 0.6710
Epoch 6/10
33/33 [==============================] - 102s 3s/step - loss: 0.6030 - accuracy: 0.6804
Epoch 7/10
33/33 [==============================] - 102s 3s/step - loss: 0.5598 - accuracy: 0.7168
Epoch 8/10
33/33 [==============================] - 112s 3s/step - loss: 0.5645 - accuracy: 0.7079
Epoch 9/10
33/33 [==============================] - 101s 3s/step - loss: 0.5202 - accuracy: 0.7403
Epoch 10/10
33/33 [==============================] - 101s 3s/step - loss: 0.5145 - accuracy: 0.7447


In [19]:
def img(path):
    img_output=cv2.imread(path,cv2.IMREAD_GRAYSCALE)
    img_output=cv2.resize(img_output,(60,60))
    img_output=np.array(img_output).reshape(-1,60,60,1)
    return img_output

In [20]:
def prediction(path):
    pred=model.predict(img(path))
    print(category[pred.argmax()])

In [21]:
model.save("dog_vs_cat.model")

INFO:tensorflow:Assets written to: dog_vs_cat.model\assets
